server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Users/Polyconseil/Documents/spring-cloud-config/config-repo
        #git:
          #uri: https://github.com/sylvestredavid/cloud_config.git
